name: Build Yandex Feed

on:
  schedule:
    - cron: '0 */6 * * *'   # каждые 6 часов (UTC)
  workflow_dispatch: {}      # запуск вручную из вкладки Actions
  push:
    branches: [ main ]       # чтобы срабатывало при обновлении скрипта

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # нужно для деплоя в gh-pages
      pages: write
      id-token: write
    concurrency:
      group: yandex-feed     # <— не даёт наложиться запускам
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Build feed
        run: node scripts/convert.js "$GOOGLE_FEED_URL" > public/yandex.yml
        env:
          GOOGLE_FEED_URL: ${{ secrets.GOOGLE_FEED_URL }}
          SHOP_NAME: "Samsung KZ"
          SHOP_COMPANY: "Samsung"
          SHOP_URL: "https://shop.samsung.com/kz_ru"
          BASE_IMAGE_ORIGIN: "https://images.samsung.com"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          force_orphan: true